version: 0.0
os: linux
files:
  - source: /apps/backend/
    destination: /home/ec2-user/mlm-backend
hooks:
# Install:
  AfterInstall:
    - location: /apps/backend/scripts/after_install.sh
      timeout: 30000
      runas: ec2-user
  ApplicationStart:
    - location: /apps/backend/scripts/application_start.sh
      timeout: 30000
      runas: ec2-user
# ValidateService: