version: 0.0
os: linux
files:
  - source: /apps/backend/
    destination: /home/ec2-user/mlm-backend
hooks:
# Install:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
# ValidateService: