version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm i -g pnpm
      - npm i -g typescript
      - pnpm install
  pre_build:
    commands:
      - echo "Starting build phase install all dependencies"
  build:
    commands:
      - pnpm
      - pnpm build

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  name: mlmFrontApp.zip 

cache:
  paths:
    - 'node_modules/**/*'  # Cache des dépendances