version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting build phase install all dependencies"

artifacts:
  files:
    - "**/*"
  base-directory: "apps/frontend"

cache:
  paths:
    - 'node_modules/**/*'  # Cache des dépendances