services:
  app-backend:
    build:
      context: .
      dockerfile: ./apps/app-backend/Dockerfile
      target: development
    command: npm run start-app-backend:dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - database
      - broker
  database:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=ivanfranck
      - POSTGRESQL_PASSWORD=paqssd163HZZ82sgdsiSf
      - POSTGRESQL_DATABASE=mylandryappdb
    volumes:
    - postgresql-persistance-data:/bitnami/postgresql

  broker:
    image: rabbitmq:3.13.6-management
    ports:
      - '5672:5672'

volumes:
  postgresql-persistance-data:
  