services:
  database:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=ivanfranck
      - POSTGRESQL_PASSWORD=paqssd163HZZ82sgdsiSf
      - POSTGRESQL_DATABASE=mylandryappdb
    volumes:
    - postgresql-persistance-data:/bitnami/postgresql
    networks:
    - myappnet

  broker:
    image: rabbitmq:3.13.6-management
    ports:
      - '5672:5672'
    networks:
    - myappnet

volumes:
  postgresql-persistance-data:
networks:
  myappnet:
    external: true
      
  