services:
  database:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=ivanfranck
      - POSTGRESQL_PASSWORD=paqssd163HZZ82sgdsiSf
      - POSTGRESQL_DATABASE=mylandryappdb
    volumes:
    - postgresql-persistance-data:/bitnami/postgresql

  broker:
    image: rabbitmq
    ports:
      - '5672:5672'

volumes:
  postgresql-persistance-data:
  