services:
  app-backend:
    build:
      context: .
      dockerfile: ./apps/app-backend/Dockerfile
      target: development
    command: npx prisma migrate deploy
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      database: 
        condition: service_healthy
      broker:
        condition: service_started
    networks:
    - myappnet
  database:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}"
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - db-data:/bitnami/postgresql
    networks:
    - myappnet
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    networks:
      - myappnet
  broker:
    image: rabbitmq:3.13.6-management
    ports:
      - '5672:5672'
    networks:
    - myappnet

volumes:
  db-data:
networks:
  myappnet:
    external: true
      
  