version: '3.8'

services:
  
  # Service de base de données PostgreSQL
  database:
    image: bitnami/postgresql
    ports:
      - '5432:5432'  # Port exposé pour PostgreSQL
    environment:
      - POSTGRESQL_USERNAME=ivanfranck
      - POSTGRESQL_PASSWORD=paqssd163HZZ82sgdsiSf
      - POSTGRESQL_DATABASE=mylandryappdb
    volumes:
      - postgresql-persistance-data:/bitnami/postgresql  # Volume pour la persistance des données
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ivanfranck"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-landry-network

  # Service de message broker RabbitMQ
  broker:
    image: rabbitmq
    ports:
      - '5672:5672'  # Port exposé pour RabbitMQ
    networks:
      - my-landry-network

  backend:
    build:
      context: ./apps/app-backend
      target: development
      args:
        - DATABASE_URL=${DATABASE_URL}
        - PORT=${PORT}
        - WHATSAPP_API_TOKEN=${WHATSAPP_API_TOKEN}
        - WHATSAPP_API_BASE_URL=${WHATSAPP_API_BASE_URL}
        - WHATSAPP_API_VERSION=${WHATSAPP_API_VERSION}
        - WHATSAPP_API_PHONE_NUMBER_ID=${WHATSAPP_API_PHONE_NUMBER_ID}
        - CODE_ALPHABET=${CODE_ALPHABET}
        - CODE_MIN_LENGTH=${CODE_MIN_LENGTH}
        - CODE_SALT=${CODE_SALT}
        - JWT_ALGORITHM=${JWT_ALGORITHM}
        - JWT_PUBLIC_KEY_PATH=${JWT_PUBLIC_KEY_PATH}
        - JWT_PRIVATE_KEY_PATH=${JWT_PRIVATE_KEY_PATH}
        - INVOICES_ROOT_PATH=${INVOICES_ROOT_PATH}
        - COMMAND_BARCODE_ROOT_PATH=${COMMAND_BARCODE_ROOT_PATH}
        - RABBIT_MQ_URI=${RABBIT_MQ_URI}
        - RABBIT_MQ_INCOMES_STATS_SERVICE_QUEUE=${RABBIT_MQ_INCOMES_STATS_SERVICE_QUEUE}
        - RABBIT_MQ_CREATE_INVOICES_SERVICE_QUEUE=${RABBIT_MQ_CREATE_INVOICES_SERVICE_QUEUE}
        - RABBIT_MQ_WHATSAPP_MESSAGING_SERVICE_QUEUE=${RABBIT_MQ_WHATSAPP_MESSAGING_SERVICE_QUEUE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env

# Définition des volumes pour la persistance des données
volumes:
  postgresql-persistance-data:

# Configuration du réseau pour la communication inter-services
networks:
  my-landry-network:
    driver: bridge
  