services:
  # Service principal de l'application backend
  app-backend:
    build:
      context: ./
      dockerfile: ./apps/app-backend/Dockerfile
      target: development
    command: ["pnpm", "start", "app-backend"]
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_started
      incomes-stats:
        condition: service_started
      invoices:
        condition: service_started
    networks:
      - my-landry-network
    ports:
      - '${PORT}:${PORT}'  # Port exposé pour l'API

  # Service de statistiques des revenus
  incomes-stats:
    build:
      context: ./
      dockerfile: ./apps/incomes-stats/Dockerfile
      target: development
    command: npm run start incomes-stats
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_started
      invoices:
        condition: service_started
    networks:
      - my-landry-network

  # Service de gestion des factures
  invoices:
    build:
      context: ./
      dockerfile: ./apps/invoices/Dockerfile
      target: development
    command: ["pnpm", "start", "invoices"]
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_started
    networks:
      - my-landry-network
      
  # Service de base de données PostgreSQL
  database:
    image: bitnami/postgresql
    ports:
      - '5432:5432'  # Port exposé pour PostgreSQL
    environment:
      - POSTGRESQL_USERNAME=ivanfranck
      - POSTGRESQL_PASSWORD=paqssd163HZZ82sgdsiSf
      - POSTGRESQL_DATABASE=mylandryappdb
    volumes:
      - postgresql-persistance-data:/bitnami/postgresql  # Volume pour la persistance des données
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ivanfranck"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-landry-network

  # Service de message broker RabbitMQ
  broker:
    image: rabbitmq
    ports:
      - '5672:5672'  # Port exposé pour RabbitMQ
    networks:
      - my-landry-network

# Définition des volumes pour la persistance des données
volumes:
  postgresql-persistance-data:

# Configuration du réseau pour la communication inter-services
networks:
  my-landry-network:
    driver: bridge
  