services:
  app-backend:
    build:
      context: .
      dockerfile: ./apps/app-backend/Dockerfile
      target: development
    command: npm run start-app-backend:prod
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      database: 
        condition: service_started
      broker:
        condition: service_started
    networks:
    - myappnet
  database:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=ivanfranck
      - POSTGRESQL_PASSWORD=paqssd163HZZ82sgdsiSf
      - POSTGRESQL_DATABASE=mylandryappdb
    volumes:
    - db-data:/bitnami/postgresql
    networks:
    - myappnet
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    networks:
      - myappnet
  broker:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
    networks:
    - myappnet

volumes:
  db-data:
networks:
  myappnet:
    external: true
      
  