export const INCOMES_STATS_SERVICE = 'INCOMES_STATS_SERVICE';
export const CREATE_INVOICES_SERVICE = 'CREATE_INVOICES_SERVICE';
export const WHATSAPP_MESSAGING_SERVICE = 'WHATSAPP_MESSAGING_SERVICE';
