export const SERVICES_QUERY_KEY = ["services_key"]
export const SERVICE_ID_QUERY_KEY = (id: number) => ["service_id_key", id]
export const CUSTOMERS_QUERY_KEY = ["customers_key"]
export const COMMANDS_QUERY_KEY = ["commands_key"]
export const COMMAND_ID_QUERY_KEY = (id: number) => ["command_id_key", id]