services:
  reverse-proxy:
    image: caddy:latest
    container_name: rever-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - mlm_network
  frontend:
    image: fridev237/mlm-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - mlm_network

networks:
  mlm_network:
    external: true