name: Deploy to VPS
on: 
    push:
        branches:
            - feature/pipeline-setup
jobs:
  build-and-publish:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: copy docker-compose file
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEYS }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | sed 's/\r$//' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
          rsync -avz ./docker  $VPS_USER@$VPS_IP:/home/$VPS_USER/mlm-project/docker
          rsync -avz ./apps/backend  $VPS_USER@$VPS_IP:/home/$VPS_USER/mlm-project/apps

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push front end image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_APP_ENVIRONMENT: ${{ secrets.VITE_APP_ENVIRONMENT }}
        run: |
          docker build --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL --build-arg VITE_APP_ENVIRONMENT=$VITE_APP_ENVIRONMENT -t $DOCKER_USERNAME/mlm-frontend:latest -f ./apps/frontend/Dockerfile ./apps/frontend
          docker push $DOCKER_USERNAME/mlm-frontend:latest

  deploy:
    runs-on:
      - ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEYS }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        with: 
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEYS }}
          script: |
            docker pull fridev237/mlm-frontend:latest
            docker compose -f ./mlm-project/docker/docker-compose.yml up -d
            
